[package]
name = "rs_gfxgraph"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_gfxgraph"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module", "auto-initialize"] }
libc = "0.2"
rs_gfxgraph_core = { path = "../rs_gfxgraph_core" }

[build-dependencies]
maturin = "1.5.0"
